# ----------------------------------------------------- 
# Window rules
# ----------------------------------------------------- 

windowrule = tile,^(Microsoft-edge)$
windowrule = tile,^(Brave-browser)$
windowrule = tile,^(Chromium)$
windowrule = float,^(pavucontrol)$
windowrule = float,^(blueman-manager)$
windowrule = float,^(nm-connection-editor)$

# -- Fix odd behaviors in IntelliJ IDEs --
#! Fix focus issues when dialogs are opened or closed
windowrulev2 = windowdance,class:^(jetbrains-.*)$,floating:1
#! Fix splash screen showing in weird places and prevent annoying focus takeovers
windowrulev2 = center,class:^(jetbrains-.*)$,title:^(splash)$,floating:1
windowrulev2 = nofocus,class:^(jetbrains-.*)$,title:^(splash)$,floating:1
windowrulev2 = noborder,class:^(jetbrains-.*)$,title:^(splash)$,floating:1

#! Center popups/find windows
windowrulev2 = center,class:^(jetbrains-.*)$,title:^( )$,floating:1
windowrulev2 = stayfocused,class:^(jetbrains-.*)$,title:^( )$,floating:1
windowrulev2 = noborder,class:^(jetbrains-.*)$,title:^( )$,floating:1
#! Disable window flicker when autocomplete or tooltips appear
windowrulev2 = nofocus,class:^(jetbrains-.*)$,title:^(win.*)$,floating:1

#windowrulev2 = noinitialfocus,class:^(jetbrains-.*),title:^(win.*)
#windowrulev2 = noborder, class:^(jetbrains-idea)(.*)$
#windowrulev2 = forceinput,class:^(jetbrains-.*)
#windowrulev2 = noinitialfocus,class:^jetbrains-(?!toolbox),floating:1
#
#
#
#
#windowrulev2=windowdance,class:^(jetbrains-.*)$
# search dialog
#windowrulev2=dimaround,class:^(jetbrains-.*)$,floating:1,title:^(?!win)
#windowrulev2=center,class:^(jetbrains-.*)$,floating:1,title:^(?!win)
# autocomplete & menus
#windowrulev2=noanim,class:^(jetbrains-.*)$,title:^(win.*)$
#windowrulev2=noinitialfocus,class:^(jetbrains-.*)$,title:^(win.*)$
#windowrulev2=rounding 0,class:^(jetbrains-.*)$,title:^(win.*)$
#

windowrule = workspace special silent,special:dropterm

