# ----------------------------------------------------- 
# Autostart
# ----------------------------------------------------- 
# Load last wallpaper and waybar with pywal colors
exec-once = ~/dotfiles/hypr/scripts/wallpaper.sh init

# Setup XDG for screen sharing
exec-once = ~/dotfiles/hypr/scripts/xdg.sh

# Start Polkit
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Load Dunst Notification Manager
exec-once = dunst

# Load GTK settings
exec-once = ~/dotfiles/hypr/scripts/gtk.sh

# Load swayidle and define the lock screen time
exec-once = ~/dotfiles/hypr/scripts/lockscreentime.sh

# Load network manager applet
# START NM APPLET
# exec-once = nm-applet --indicator
# END NM APPLET

# Load cliphist history
exec-once = wl-paste --watch cliphist store

# Initialize swww
exec-once = swww query || swww init



exec-once = fcitx5 -d

# Start ML4W Welcome App
exec-once = ~/dotfiles/hypr/scripts/ml4w-welcome-autostart.sh
exec-once = systemctl --user import-environment WAYLAND_DISPLAY
exec-once = xprop -root -format _XWAYLAND_GLOBAL_OUTPUT_SCALE 32c -set _XWAYLAND_GLOBAL_OUTPUT_SCALE 2
exec-once =  xrdb -merge ~/.Xresources

exec-once= [workspace special:dropterm silent] kitty --class kitty-dropterm
exec-once=[workspace 1 silent] chromium
#exec-once=[workspace 7 silent] 64gram-desktop
#exec-once= ~/dotfiles/hypr/scripts/launch_pycharm.sh
#exec-once= ~/dotfiles/hypr/scripts/launch_webstrom.sh
exec-once= ~/dotfiles/hypr/scripts/movewindow.sh
