# ----------------------------------------------------- 
# Environment Variables
# name: "Default"
# ----------------------------------------------------- 

#env = GDK_SCALE,2
env = QT_QPA_PLATFORMTHEME,qt5ct # change to qt6ct if you have that
env=XMODIFIERS, @im=fcitx
env=QT_IM_MODULE, fcitx
env=SDL_IM_MODULE, fcitx
env=GDK_BACKEND, wayland,x11
env=QT_QPA_PLATFORM, wayland;xcb
env=QT_WAYLAND_DISABLE_WINDOWDECORATION, 1
env=QT_AUTO_SCREEN_SCALE_FACTOR, 1
env=CLUTTER_BACKEND, wayland
env=ADW_DISABLE_PORTAL, 1
env=XCURSOR_SIZE, 64
